name: Auto tag

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Auto tag
      uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
