name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Trigger to build framework
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EVENT: making-framework
        ORG: quanlebbv
        REPO: MyFrameworkDistribution
      run: |
        curl -X POST https://api.github.com/repos/quanlebbv/MyFrameworkDistribution/dispatches -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -d '{"event_type":"making-framework"}'
