name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run shell
      run: |
        sh ./build_xcframework.sh
