name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EVENT: making-framework
        ORG: quanlebbv
        REPO: MyFrameworkDistribution
      run: |
        curl -X POST https://api.github.com/repos/quanlebbv/MyFrameworkDistribution/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u $GITHUB_TOKEN \
          --data '{"event_type": "making-framework"}'
