name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        EVENT: making-framework
        ORG: quanlebbv
        REPO: MyFrameworkDistribution
      run: |
        curl -X POST https://api.github.com/repos/$ORG/$REPO/dispatches \
        -H 'Accept: application/vnd.github.v3+json' \
        -u quanlebbv:$GITHUB_TOKEN \
        --data '{"event_type": "$EVENT"}'
