name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        EVENT: making-framework
        ORG: quanlebbv
        REPO: MyFrameworkDistribution
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/$ORG/$REPO/dispatches \
          -d '{"event_type":"$EVENT"}'
