name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT: "making-framework"
        ORG: "quanlebbv"
        REPO: "MyFrameworkDistribution"
      run: |
        curl -d "{\"event_type\": \"making-framework\"}" -H "Content-Type: application/json" -H "Authorization: ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/quanlebbv/MyFrameworkDistribution/dispatches"
