name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: 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
        EVENT: making-framework
        ORG: quanlebbv
        REPO: MyFrameworkDistribution
      run: |
        curl -d "{\"event_type\": \"making-framework\"}" -H "Content-Type: application/json" -H "Authorization: token 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" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/quanlebbv/MyFrameworkDistribution/dispatches"
